name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    name: Check
    runs-on: Linux
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 8
  unit-tests:
    name: Unit tests
    runs-on: Linux
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 8
      - name: Unit tests
        run: ./gradlew testDebugUnitTest

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: Linux
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'zulu'
          java-version: 8
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.21.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest
