name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt-openj9'
          java-version: 11
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt-openj9'
          java-version: 11
      - name: Unit tests
        run: ./gradlew testDebugUnitTest

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macos-10.15
    timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        api-level: [ 22, 25, 29 ]
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - name: gradle wrapper
        uses: gradle/wrapper-validation-action@v1.0.4
      - uses: actions/setup-java@v2.3.1
        with:
          distribution: 'adopt-openj9'
          java-version: 11
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2.21.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest
